---
- name: Deploy awall configuration
  ansible.builtin.template:
    src: templates/awall.j2
    dest: /etc/awall/optional/mempool.json
    owner: root
    group: root
    mode: '0644'

- name: Enable mempool policy
  community.general.awall:
    name: mempool
    state: enabled
    activate: true