---
- name: Install build dependencies
  ansible.builtin.apk:
    name: "{{ mempool_build_deps | join(',') }}"
    state: latest
    update_cache: true

- name: Install runtime dependencies
  ansible.builtin.apk:
    name: "{{ mempool_runtime_deps | join(',') }}"
    state: latest
    update_cache: true