---
- name: Manage service(s)
  hosts: all
  gather_facts: true
  tasks:
    - ansible.builtin.set_fact:
        def_service_list: >-
          {{
            service_list.split(',')
            | map('regex_replace', 'awall', 'iptables,ip6tables')
            | join(',')
            | split(',')
          }}

    - ansible.builtin.service:
        name: "{{ item }}"
        state: "{{ service_state }}"
      loop: "{{ def_service_list }}"
      when:
        - service_state is defined and service_state != ""
        - service_enabled is not defined or service_enabled == ""

    - ansible.builtin.service:
        name: "{{ item }}"
        enabled: "{{ service_enabled }}"
      loop: "{{ def_service_list }}"
      when:
        - service_state is not defined or service_state == ""
        - service_enabled is defined and service_enabled != ""

    - ansible.builtin.service:
        name: "{{ item }}"
        state: "{{ service_state }}"
        enabled: "{{ service_enabled }}"
      loop: "{{ def_service_list }}"
      when:
        - service_state is defined and service_state != ""
        - service_enabled is defined and service_enabled != ""