---
- name: Upgrade all nodes
  hosts: all
  gather_facts: true
  roles:
    - upgrade

- name: Prepare all nodes
  hosts: all
  gather_facts: true
  roles:
    - prepare

- name: Install firewall
  hosts: all
  gather_facts: true
  roles:
    - firewall

- name: Install reverse proxy
  hosts: all
  gather_facts: true
  roles:
    - reverse_proxy

- name: Install tor and i2p
  hosts: all
  gather_facts: true
  roles:
    - privacy

- name: Install bitcoin
  hosts: all
  gather_facts: true
  roles:
    - bitcoin

- name: Install electrum
  hosts: all
  gather_facts: true
  tasks:
    - name: Include the electrum role
      ansible.builtin.include_role:
        name: "{{ electrum_role }}"

- name: Install explorer(s)
  hosts: all
  gather_facts: true
  tasks:
    - name: Include the explorer role
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ explorer_role }}"

- name: Install public pool
  hosts: all
  gather_facts: true
  tasks:
    - name: Include the public_pool role
      ansible.builtin.include_role:
        name: public_pool
      when: pool_role | default(false)

- name: Install lightning
  hosts: all
  gather_facts: true
  tasks:
    - name: Include the lightning role
      ansible.builtin.include_role:
        name: "{{ lightning_role }}"

- name: Install nostr
  hosts: all
  gather_facts: true
  tasks:
    - name: Include the nostr role
      ansible.builtin.include_role:
        name: nostr-rs-relay
      when: nostr_role | default(false)