---
- name: Deploy caddy configuration
  ansible.builtin.template:
    src: templates/caddy.j2
    dest: /etc/caddy/fulcrum.caddy
    owner: root
    group: root
    mode: '0644'

- name: Restart Caddy service
  ansible.builtin.service:
    name: caddy
    state: restarted