---
- block:
  - name: Download banner.txt
    ansible.builtin.get_url:
      url: https://gist.githubusercontent.com/doitwithnotepad/4472a92414223672d9ab4c3b55d0cd23/raw/c68c8a8ba7f0a0ce3b3bb3bc525c5ad6745af592/banner.txt
      dest: /etc/fulcrum/banner.txt
      owner: fulcrum
      group: fulcrum
      mode: '0644'

  - name: Fulcrum configuration
    ansible.builtin.lineinfile:
      path: /etc/fulcrum/fulcrum.conf
      regexp: '^#?\s*{{ item.lstrip("#").split("=")[0] | regex_escape }}\s*='
      line: "{{ item }}"
      state: present
    loop: "{{ fulcrum_config_options }}"

  - include_tasks: tor.yaml
    when: electrum_tor

  - name: Fulcrum logrotate script
    ansible.builtin.template:
      src: logrotate.j2
      dest: /etc/logrotate.d/fulcrum
      mode: '0644'

  - name: Fulcrum init script
    ansible.builtin.template:
      src: init.j2
      dest: /etc/init.d/fulcrum
      mode: '0755'

  - name: Start fulcrum
    ansible.builtin.service:
      name: fulcrum
      enabled: true
      state: started
  when: install_result is not failed