---
- name: Install build dependencies
  ansible.builtin.apk:
    name: "{{ fulcrum_build_deps | join(',') }}"
    state: latest
    update_cache: true
  when: fulcrum_build_deps

- name: Install runtime dependencies
  ansible.builtin.apk:
    name: "{{ fulcrum_runtime_deps | join(',') }}"
    state: latest
    update_cache: true
  when: fulcrum_runtime_deps