---  
- block:
  - name: Configure fulcrum
    ansible.builtin.shell:
      cmd: |
        qmake6 \
          Fulcrum.pro \
          -o build/
    args:
      chdir: /tmp/Fulcrum
    register: configure_result

  - name: Compile fulcrum
    ansible.builtin.shell:
      cmd: |
        CC=gcc \
        CXX=g++ \
        make -C build
    args:
      chdir: /tmp/Fulcrum
    register: make_result
    when: configure_result is not failed
  become_user: "{{ ansible_user }}"
  when: verify_result is not failed

  rescue:
    - ansible.builtin.meta: notify
      args:
        handler_name: cleanup

- block:
  - name: Install Fulcrum binary
    ansible.builtin.copy:
      src: /tmp/Fulcrum/build/Fulcrum
      dest: /usr/bin/Fulcrum
      owner: root
      group: root
      mode: '0755'
      remote_src: yes

  - name: Install FulcrumAdmin binary
    ansible.builtin.copy:
      src: /tmp/Fulcrum/FulcrumAdmin
      dest: /usr/bin/FulcrumAdmin
      owner: root
      group: root
      mode: '0755'
      remote_src: yes

  - name: Ensure /etc/fulcrum directory exists
    ansible.builtin.file:
      path: /etc/fulcrum
      state: directory
      owner: fulcrum
      group: fulcrum
      mode: '0755'

  - name: Install Fulcrum config
    ansible.builtin.copy:
      src: /tmp/Fulcrum/doc/fulcrum-example-config.conf
      dest: /etc/fulcrum/fulcrum.conf
      owner: fulcrum
      group: fulcrum
      mode: '0660'
      remote_src: yes

  - name: Strip binaries
    ansible.builtin.shell:
      cmd: strip /usr/bin/Fulcrum
  when: make_result is not failed
  always:
    - ansible.builtin.meta: notify
      args:
        handler_name:
          - cleanup
          - remove_build_deps