---
- name: Install global dependencies
  community.general.apk:
    name: openssl,qemu-guest-agent
    state: latest
    update_cache: true

- name: Create file /etc/profile.d/defaults.sh
  ansible.builtin.file:
    path: "/etc/profile.d/defaults.sh"
    state: touch
    mode: '0644'

- name: Populate /etc/profile.d/defaults.sh
  ansible.builtin.lineinfile:
    path: "/etc/profile.d/defaults.sh"
    state: present
    regexp: "^{{ item.key }}="
    line: "export {{ item.key }}=\"{{ item.value}}\""
  with_items: "{{ env_vars }}"

- name: Source changes
  ansible.builtin.shell:
    cmd: . /etc/profile.d/defaults.sh

- include_tasks: disks.yaml
  when: second_disk

- include_tasks: swap.yaml
  when: swap