---
- name: Install dependencies
  community.general.apk:
    name: gnupg,openssl,qemu-guest-agent
    state: latest
    update_cache: true

- name: Enable qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true
    state: started

- include_tasks: disks.yaml
  when: second_disk