---
- name: Add Hidden Service SSH server configuration
  ansible.builtin.blockinfile:
    path: /etc/tor/torrc
    insertafter: '## This section is just for location-hidden services ##'
    block: |
      # Hidden Service SSH server
      HiddenServiceDir /var/lib/tor/ssh/
      HiddenServiceVersion 3
      HiddenServicePoWDefensesEnabled 1
      HiddenServicePort 22 127.0.0.1:22

- name: Get the SSH Onion address
  ansible.builtin.command:
    cmd: cat /var/lib/tor/ssh/hostname
  register: ssh_onion_address

- name: Display SSH Onion address
  ansible.builtin.debug:
    msg: "SSH Onion address: {{ ssh_onion_address.stdout }}"