---
- name: Install awall
  community.general.apk:
    name: awall,iptables,ip6tables
    state: latest
    update_cache: true

- name: Add the ip_tables module and make sure it is loaded after reboots
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - ip_tables
    - ip6_tables

- name: Deploy awall base-config and ssh
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/awall/optional/{{ item }}.json"
    owner: root
    group: root
    mode: '0644'
  loop:
    - base-config
    - ssh

- name: Enable base-config and ssh policy
  community.general.awall:
    name: [ base-config ssh ]
    state: enabled
    activate: true

- name: Make iptables start on boot and start it
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - iptables
    - ip6tables