---
- name: Install ufw
  community.general.apk:
    name: ufw,ip6tables
    state: latest
    update_cache: true

- name: Deny incoming connections
  community.general.ufw:
    policy: deny
    direction: incoming

- name: Allow outgoing connections
  community.general.ufw:
    policy: allow
    direction: outgoing

- name: Allow SSH
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
    comment: "Allow SSH"

- name: Set logging
  community.general.ufw:
    logging: 'off'
    state: enabled

- name: Make ufw start on boot
  ansible.builtin.service:
    name: ufw
    enabled: true
    state: started