---
- block:
  - name: Create public-pool system group
    ansible.builtin.group:
      system: true
      name: public-pool
      state: present

  - name: Create public-pool system user
    ansible.builtin.user:
      system: true
      password: "!"
      create_home: false
      home: /dev/null
      shell: /sbin/nologin
      group: public-pool
      comment: "public-pool"
      name: public-pool
      state: present

  - name: Add user public-pool to bitcoin group
    ansible.builtin.user:
      name: public-pool
      groups: bitcoin
      append: true
      state: present

  - name: Add user {{ ansible_user }} to public-pool group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: public-pool
      append: true
      state: present

  - name: Add user public-pool to tor group
    ansible.builtin.user:
      name: public-pool
      groups: tor
      append: true
      state: present

  # Firewall
  - include_tasks: awall.yaml
    when: firewall_role == 'awall'

  - include_tasks: ufw.yaml
    when: firewall_role == 'ufw'

  # Reverse Proxy
  - include_tasks: caddy.yaml
    when: reverse_proxy_role == 'caddy'

  - include_tasks: nginx.yaml
    when: reverse_proxy_role == 'nginx'

  - block:
    - name: Download public-pool backend repository
      ansible.builtin.shell:
        cmd: git clone https://github.com/benjamin-wilson/public-pool.git
      args:
        chdir: /tmp
      register: clone_result

    - name: Download public-pool frontend repository
      ansible.builtin.shell:
        cmd: git clone https://github.com/benjamin-wilson/public-pool-ui.git
      args:
        chdir: /tmp
      register: clone_result

    - name: Checkout public-pool and public-pool-ui repositories
      ansible.builtin.shell:
        cmd: git checkout {{ item.commit }}
      args:
        chdir: "{{ item.dir }}"
      when: item.commit != "latest"
      with_items:
        - { dir: '/tmp/public-pool', commit: '{{ public_pool_commit }}' }
        - { dir: '/tmp/public-pool-ui', commit: '{{ public_pool_ui_commit }}' }
    become_user: "{{ ansible_user }}"

  rescue:
    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /tmp/public-pool
        - /tmp/public-pool-ui