---
- name: Add Hidden Service Public Pool server configuration
  ansible.builtin.blockinfile:
    path: /etc/tor/torrc
    insertafter: '## This section is just for location-hidden services ##'
    block: |
      # Hidden Service Public Pool Space
      HiddenServiceDir /var/lib/tor/public-pool/
      HiddenServiceVersion 3
      HiddenServicePoWDefensesEnabled 1
      HiddenServicePort 443 127.0.0.1:{{ public_pool_ui_port_ssl }}

- name: Get the public-pool Onion address
  ansible.builtin.command:
    cmd: cat /var/lib/tor/public-pool/hostname
  register: public_pool_onion_address

- name: Display public-pool Onion address
  ansible.builtin.debug:
    msg: "Public Pool Onion address: {{ public_pool_onion_address.stdout }}"