---
- name: Update repositories and update package apk-tools to latest version
  community.general.apk:
    name: apk-tools
    state: latest
    update_cache: true

- name: Get current kernel version in use
  ansible.builtin.shell: |
    var="$(uname -r)"
    printf "%s\n" "${var%%-*}"
  register: current_kernel_version

# Change 'linux-virt' to 'linux-lts'/'linux-edge' kernel package (set correct package name here)
- name: Get installed kernel package version
  ansible.builtin.shell: |
    ker="linux-virt"
    var="$(apk info $ker | grep -m 1 $ker)"
    var="${var#$ker-*}"
    var="${var%-*}"
    printf "%s\n" "$var"
  register: installed_kernel_version

- name: Update all installed packages to the latest versions
  community.general.apk:
    upgrade: true

- name: Reboot the system
  reboot:
    connect_timeout: 5
    reboot_command: "{{ custom_reboot_command | default(omit) }}"
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: current_kernel_version.stdout != installed_kernel_version.stdout