---
- name: Deploy awall configuration
  ansible.builtin.template:
    src: templates/awall.j2
    dest: /etc/awall/optional/electrs.json
    owner: root
    group: root
    mode: '0644'

- name: Enable electrs policy
  community.general.awall:
    name: electrs
    state: enabled
    activate: true