---
- block:
  - name: Compile electrs
    ansible.builtin.shell:
      cmd: |
        cargo auditable build \
            --bin electrs \
            --features "metrics_process" \
            --release \
            --locked \
            --jobs "$(nproc)"
    args:
      chdir: /tmp/electrs
    register: compile_result
  become_user: "{{ ansible_user }}"
  when: verify_result is not failed

  rescue:
    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: "/tmp/electrs"

- block:
  - name: Install electrs binary
    ansible.builtin.copy:
      src: /tmp/electrs/target/release/electrs
      dest: /usr/bin/electrs
      owner: root
      group: root
      mode: '0755'
      remote_src: yes

  - name: Ensure /etc/electrs directory exists
    ansible.builtin.file:
      path: /etc/electrs
      state: directory
      owner: electrs
      group: electrs
      mode: '0755'

  - name: Install electrs config
    ansible.builtin.copy:
      src: /tmp/electrs/doc/config_example.toml
      dest: /etc/electrs/config.toml
      owner: electrs
      group: electrs
      mode: '0660'
      remote_src: yes

  - name: Strip binaries
    ansible.builtin.shell:
      cmd: strip /usr/bin/electrs
  when: compile_result is not failed

- name: Cleanup
  ansible.builtin.file:
    state: absent
    path: "/tmp/electrs"

- name: Remove build deps
  community.general.apk:
    name: "{{ electrs_build_deps | join(',') }}"
    state: absent