---
- name: Deploy awall configuration
  ansible.builtin.template:
    src: templates/awall.j2
    dest: /etc/awall/optional/btcrpcexpl.json
    owner: root
    group: root
    mode: '0644'

- name: Enable btc-rpc-explorer policy
  community.general.awall:
    name: btcrpcexpl
    state: enabled
    activate: true