---
- block:
  - name: Get version number of latest btc-rpc-explorer release
    ansible.builtin.shell:
      cmd: wget -qO- 'https://api.github.com/repos/janoside/btc-rpc-explorer/releases/latest' | grep '"tag_name":' | cut -d'"' -f4 | sed 's/^v//'
    register: btcrpc_version_result

  - name: Set btcrpc_version fact
    set_fact:
      btcrpc_version: "{{ btcrpc_version_result.stdout }}"
  when: btcrpc_version == "latest"

- block:
  - name: Create btc-rpc-explorer system group
    ansible.builtin.group:
      system: true
      name: btc-rpc-explorer
      state: present

  - name: Create btc-rpc-explorer system user
    ansible.builtin.user:
      system: true
      password: "!"
      create_home: false
      home: /dev/null
      shell: /sbin/nologin
      group: btc-rpc-explorer
      comment: "btc-rpc-explorer"
      name: btc-rpc-explorer
      state: present

  - name: Add user btc-rpc-explorer to bitcoin group
    ansible.builtin.user:
      name: btc-rpc-explorer
      groups: bitcoin
      append: true
      state: present

  - name: Add user {{ ansible_user }} to btc-rpc-explorer group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: btc-rpc-explorer
      append: true
      state: present

  # Firewall
  - include_tasks: awall.yaml
    when: firewall_role == 'awall'

  - include_tasks: ufw.yaml
    when: firewall_role == 'ufw'

  # Reverse Proxy
  - include_tasks: caddy.yaml
    when: reverse_proxy_role == 'caddy'

  - include_tasks: nginx.yaml
    when: reverse_proxy_role == 'nginx'

  - block:
    - name: Download btc-rpc-explorer repository
      ansible.builtin.shell:
        cmd: git clone --branch v{{ btcrpc_version }} https://github.com/janoside/btc-rpc-explorer.git
      args:
        chdir: /tmp

    - name: Import PGP keys from GitHub repository
      ansible.builtin.shell:
        cmd: wget -qO- "{{ btcrpc_keys_url }}" | gpg --import
      register: import_keys_result

    - name: Debug import_keys_result
      ansible.builtin.debug:
        var: import_keys_result.stderr_lines

    - name: Verify btc-rpc-explorer tag
      ansible.builtin.shell:
        cmd: git verify-commit v{{ btcrpc_version }}
      args:
        chdir: /tmp/btc-rpc-explorer
      register: verify_result
      failed_when: "'Good signature' not in verify_result.stderr"

    - name: Debug verify_result
      ansible.builtin.debug:
        var: verify_result.stderr_lines
    become_user: "{{ ansible_user }}"

  rescue:
    - name: Cleanup
      ansible.builtin.file:
        state: absent
        path: /tmp/btc-rpc-explorer
  when: btcrpc_version_result is not failed or btcrpc_version != "latest"