---
# System options
ethernet: eth0
swap: true
swap_size: 4 # in GB
second_disk: false
second_disk_dev: /dev/sdb
second_disk_part: true
second_disk_format: ext4

# Microbolt options
firewall_role: awall # awall or ufw
reverse_proxy_role: caddy # caddy or nginx
bitcoin_role: knots # knots or core
electrum_role: fulcrum # fulcrum or electrs
explorer_role: # btcrpc and/or mempool
  - btcrpc
  - mempool
pool_role: true # public_pool
lightning_role: lnd # lnd or cln (not ready yet)
nostr_role: true # nostr-rs-relay + umbrel-nostr-relay

# Tor options
tor_ssh: false
tor_electrum: false
tor_btcrpc: false
tor_mempool: false
tor_public_pool: false

# Bitcoin options
bitcoin_version: 26.1.knots20240325 # latest or specific version
bitcoin_man: false
bitcoin_rpc_username: microbolt
bitcoin_rpc_password: passwd
bitcoin_dbcache: 4096

# Electrum options
electrum_version: latest # latest or specific version
electrum_port_tcp: 50001
electrum_port_ssl: 50002

# BTC RPC Explorer options
btcrpc_version: latest # latest or specific version
btcrpc_port_tcp: 3002
btcrpc_port_ssl: 4000
btcrpc_theme: dark # dark or light
btcrpc_slow_device_mode: false
btcrpc_privacy_mode: true
btcrpc_security_mode: false
btcrpc_password: passwd # only if security_mode is true

# Mempool options
mempool_version: latest # latest or specific version
mempool_port_tcp: 8999
mempool_port_ssl: 4081
mempool_redis: true

# Public Pool options

# Lightning options
lnd_slow_device_mode: false

# Nostr options

################################################################################
# DO NOT EDIT BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING               #
################################################################################

# Ansible options
ansible_user: satoshi
ansible_become: true
ansible_become_method: doas

# Compile options
env_vars:
  - key: EDITOR
    value: vi
  - key: SU
    value: "{{ ansible_become_method }}"
  - key: CC
    value: clang
  - key: CXX
    value: clang++
  - key: CFLAGS
    value: "-O3 -pipe -march=native -fPIE"
  - key: CXXFLAGS
    value: "-O3 -pipe -march=native -fPIE"
  - key: LDFLAGS
    value: "-pie -Wl,--as-needed"
  - key: MAKEFLAGS
    value: -j$(nproc)
  - key: CARGO_HOME
    value: ./.cargo
  - key: npm_config_cache
    value: ./npm-cache
  - key: npm_config_devdir
    value: ./.gyp
  - key: ROCKSDB_INCLUDE_DIR
    value: /usr/include
  - key: ROCKSDB_LIB_DIR
    value: /usr/lib
  - key: PROTOC
    value: protoc-c

# Caddy options
caddy_base_url: https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}

# Bitcoin options
bitcoin_base_url: >-
  {%- if bitcoin_role == 'knots' -%}
    https://bitcoinknots.org/files/{{ bitcoin_version | regex_replace('\..*$', '') }}.x/{{ bitcoin_version }}
  {%- elif bitcoin_role == 'core' -%}
    https://bitcoincore.org/bin/bitcoin-core-{{ bitcoin_version }}
  {%- endif -%}
bitcoin_keys_url: >-
  {%- if bitcoin_role == 'knots' -%}
    https://api.github.com/repos/bitcoinknots/guix.sigs/contents/builder-keys
  {%- elif bitcoin_role == 'core' -%}
    https://api.github.com/repositories/355107265/contents/builder-keys
  {%- endif -%}
bitcoin_build_deps:
  - autoconf
  - automake
  - boost-dev
  - clang
  - chrpath
  - file
  - gnupg
  - libevent-dev
  - libtool
  - make
  - pkgconf
  - zeromq-dev
bitcoin_runtime_deps:
  - libevent
  - libsodium
  - libstdc++
  - libzmq
  - "{% if bitcoin_man %}man-pages{% endif %}"
  - "{% if bitcoin_man %}mandoc{% endif %}"
bitcoin_config_options:
  - assumevalid=0
  - blockfilterindex=1
  - blocksonly=1
  - coinstatsindex=1
  - dbcache={{ bitcoin_dbcache }}
  - txindex=1
  - i2psam=127.0.0.1:7656
  - onion=127.0.0.1:9050
  - peerblockfilters=1
  - peerbloomfilters=1
  - zmqpubhashblock=tcp://127.0.0.1:8433
  - zmqpubrawblock=tcp://127.0.0.1:28332
  - zmqpubrawtx=tcp://127.0.0.1:28333
  - datacarrier=0
  - permitbaremultisig=0
  - "debug=i2p\ndebug=tor"
  - server=1

# Electrum options
fulcrum_keys_url: https://raw.githubusercontent.com/Electron-Cash/keys-n-hashes/master/pubkeys/calinkey.txt
fulcrum_build_deps:
  - autoconf
  - g++
  - git
  - gnupg
  - jemalloc-dev
  - lz4-dev
  - make
  - pkgconf
  - qt6-qtbase-dev
  - rocksdb-dev
  - zeromq-dev
fulcrum_runtime_deps:
  - jemalloc
  - libzmq
  - qt6-qtbase
  - rocksdb
fulcrum_config_options:
  - "#datadir = /path/to/a/dir"
  - "#rpcuser = Bob_The_Banker"
  - "#rpcpassword = hunter1"
  - "rpccookie = /var/lib/bitcoind/.cookie"
  - "tcp = 0.0.0.0:{{ electrum_port_tcp }}"
  - "banner = /etc/fulcrum/banner.txt"
  - "peering = false"

electrs_keys_url: https://romanzey.de/pgp.txt
electrs_build_deps:
  - cargo
  - cargo-auditable
  - clang-dev
  - cmake
  - git
  - gnupg
  - rocksdb-dev
electrs_runtime_deps:
  - rocksdb
electrs_config_options:
  - "cookie_file = \"/var/lib/bitcoind/.cookie\""
  - "#db_dir = \"/some/fast/storage/with/big/size\""
  - "electrum_rpc_addr = \"127.0.0.1:{{ electrum_port_tcp }}\""
  - "daemon_dir = \"/var/lib/bitcoind\""

# BTC RPC Explorer options
btcrpc_keys_url: https://github.com/janoside.gpg
btcrpc_build_deps:
  - git
  - gnupg
  - npm
btcrpc_runtime_deps:
  - nodejs-current
btcrpc_config_options:
  - BTCEXP_PORT={{ btcrpc_port_tcp }}
  - BTCEXP_BITCOIND_HOST=127.0.0.1
  - BTCEXP_BITCOIND_PORT=8332
  - BTCEXP_BITCOIND_COOKIE=/var/lib/bitcoind/.cookie
  - BTCEXP_ADDRESS_API=electrum
  - BTCEXP_ELECTRUM_SERVERS=tcp://127.0.0.1:{{ electrum_port_tcp }}
  - BTCEXP_SLOW_DEVICE_MODE={{ btcrpc_slow_device_mode | lower }}
  - "{% if btcrpc_slow_device_mode %}BTCEXP_BITCOIND_RPC_TIMEOUT=10000{% endif %}"
  - BTCEXP_UI_THEME={{ btcrpc_theme }}
  - BTCEXP_PRIVACY_MODE={{ btcrpc_privacy_mode | lower}}
  - BTCEXP_NO_RATES={{ btcrpc_privacy_mode | lower }}
  - BTCEXP_DEMO={{ btcrpc_security_mode | lower }}
  - "{% if btcrpc_security_mode %}BTCEXP_BASIC_AUTH_PASSWORD={{ btcrpc_password }}{% endif %}"

# Mempool options
mempool_keys_url: https://github.com/wiz.gpg
mempool_build_deps:
  - cargo
  - git
  - gnupg
  - npm
  - py3-mysqlclient
  - rsync
mempool_runtime_deps:
  - mariadb
  - mariadb-client
  - nodejs-current
  - "{% if mempool_redis %}redis{% endif %}"
mempool_config_options:
  MEMPOOL:
    HTTP_PORT: '{{ mempool_port_tcp }}'
    CACHE_ENABLED: false
    INDEXING_BLOCKS_AMOUNT: 52560
    STDOUT_LOG_MIN_PRIORITY: 'info'
  CORE_RPC:
    USERNAME: ''
    PASSWORD: ''
    COOKIE: true
    COOKIE_PATH: '/var/lib/bitcoind/.cookie'
  ESPLORA:
    REST_API_URL: ''
    UNIX_SOCKET_PATH: ''
  SECOND_CORE_RPC:
    HOST: ''
  DATABASE:
    SOCKET: '/var/run/mysqld/mysqld.sock'
    PASSWORD: ''
  SOCKS5PROXY:
    ENABLED: true
  REDIS:
    ENABLED: "{{ mempool_redis }}"
    UNIX_SOCKET_PATH: '/var/run/redis/redis.sock'

# Public Pool options
public_pool_keys_url:
public_pool_build_deps:
  - git
  - npm
public_pool_runtime_deps:
  - nodejs-current
public_pool_config_options:

# Lightning options
lnd_keys_url: https://raw.githubusercontent.com/lightningnetwork/lnd/master/scripts/keys/roasbeef.asc
lnd_build_deps:
  - git
  - go
  - gnupg
  - make

# Nostr options
nostr_keys_url:
nostr_build_deps:
  - git
  - go
  - gnupg
  - make
nostr_runtime_deps:
  - nodejs-current
nostr_config_options:
  - NOSTR_RPC_PORT=8080
  - NOSTR_RPC_HOST=